compatibility_date = "2024-09-23"
main = "src/index.ts"
minify = true
name = "edgestore"
upload_source_maps = true
workers_dev = false

[[routes]]
pattern = "edgestore.link/*"
zone_name = "edgestore.link"

[assets]
directory = "./public/"

[observability]
enabled = true

[dev]
host = '127.0.0.1:8787'
