name = "edgestore"

compatibility_date = "2024-09-23"
main = "src/index.ts"
workers_dev = false

[[routes]]
pattern = "edgestore.link/*"
zone_id = "f0d3d3512bee2ee11268d6be21a4c83a"

[assets]
directory = "./public/"

[observability]
enabled = true

[dev]
host = '127.0.0.1:8787'
