name = "edgestore"

compatibility_date = "2024-09-23"
main = "src/index.ts"
workers_dev = false

[[routes]]
pattern = "store.jiangzhexin.xyz/*"
zone_id = "dd4d9ed822e9726c40eea6e1e1f8c3b9"

[assets]
directory = "./public/"

[observability]
enabled = true
